// <auto-generated>
// Generated by Tools/Red Dot/Config Database.
// Edit RedDotConfigDatabase.asset, then click Write RedDotPath.cs.
// </auto-generated>

namespace GF_Mahjong.RedDot
{
    public static class RedDotPath
    {
        public const string Main = "Main";
        public const string MainTask = "Main.Task";
        public const string MainTaskChest = "Main.Task.Chest";
        public const string MainTaskChest1 = "Main.Task.Chest.1";
        public const string MainTaskChest2 = "Main.Task.Chest.2";
        public const string MainTaskChest3 = "Main.Task.Chest.3";
        public const string MainTaskDaily = "Main.Task.Daily";
        public const string MainTaskAchievement = "Main.Task.Achievement";
        public const string MainShop = "Main.Shop";
        public const string MainShopFree = "Main.Shop.Free";
        public const string MainRank = "Main.Rank";
        public const string MainRankSeasonReward = "Main.Rank.SeasonReward";
        public const string Game = "Game";
        public const string GameItem = "Game.Item";
    }
}
